kedify-proxy: preStop hook with connection drain check
Signed-off-by: Jan Wozniak <wozniak.jan@gmail.com>

diff --git a/kedify-proxy/templates/envoy-deployment.yaml b/kedify-proxy/templates/envoy-deployment.yaml
--- a/kedify-proxy/templates/envoy-deployment.yaml
+++ b/kedify-proxy/templates/envoy-deployment.yaml
@@ -48,10 +48,34 @@ spec:
                   - /bin/bash
                   - -c
                   - |
-                    echo "Gracefully shutting down kedify-proxy"
+                    function log() {
+                      echo "[$(date -u +'%Y-%m-%d %T.%3N')][1][info][prestop-hook] $1" > /proc/1/fd/1
+                    }
+                    log "Gracefully shutting down kedify-proxy"
                     exec 3<>/dev/tcp/localhost/{{ .Values.service.adminPort }}
-                    echo -e 'POST /healthcheck/fail HTTP/1.1\r\nHost: localhost\r\nContent-Length:0\r\n\r\n' >&3
-                    sleep {{ .Values.pod.preStopHookWaitSeconds }}
+                    echo -e 'POST /healthcheck/fail HTTP/1.1\r\nHost: preStopHook\r\nContent-Length:0\r\nConnection: close\r\n\r\n' >&3
+                    response=$(cat <&3)
+
+                    timeout={{ .Values.pod.terminationGracePeriodSeconds }}
+                    interval=1
+                    elapsed=0
+
+                    while [[ "$elapsed" -lt "$timeout" ]]; do
+                      exec 3<>/dev/tcp/localhost/{{ .Values.service.adminPort }}
+                      echo -e 'GET /stats?filter=http.kedify-proxy.downstream_cx_active HTTP/1.1\r\nHost: preStopHook\r\nConnection: close\r\n\r\n' >&3
+                      response=$(cat <&3)
+                      active_connections=$(echo "$response" | awk '/http.kedify-proxy.downstream_cx_active:/{print $2}')
+                      log "Try $elapsed/$timeout; active connections: $active_connections"
+                      if [[ "$active_connections" -eq 0 ]]; then
+                        log "No active connections, terminating in {{ .Values.pod.preStopHookWaitSeconds }} seconds"
+                        sleep {{ .Values.pod.preStopHookWaitSeconds }}
+                        exit 0
+                      fi
+                      sleep $interval
+                      elapsed=$((elapsed + interval))
+                    done
+                    log "Timeout reached with active connections: $active_connections, terminating anyway"
+                    exit 1
           env:
             - name: ENVOY_UID
               value: {{ .Values.pod.containerSecurityContext.runAsUser | quote }}
